import { StyleSheet } from "react-native";
import { colors, spacing } from "@/constants/theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#141216", paddingHorizontal: spacing.lg },
  centered: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.md },
  muted: { fontSize: 14, color: colors.sec, textAlign: "center" },
  topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  progress: { fontSize: 14, fontWeight: "800", color: colors.onImage },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.glassFill,
    borderWidth: 1,
    borderColor: colors.glassBorder,
  },
  segments: { flexDirection: "row", gap: 4, marginTop: spacing.sm },
  segTrack: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  segFill: { flex: 1, backgroundColor: colors.onImage },
  cardWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
  card: { borderRadius: 20, overflow: "hidden", backgroundColor: colors.inset },
  stacked: { position: "absolute", opacity: 0.5 },
  cardMeta: { position: "absolute", left: 20, right: 20, bottom: 20, gap: 4 },
  cardTitle: { fontSize: 22, fontWeight: "800", letterSpacing: -0.6, color: colors.onImage },
  cardRegion: { fontSize: 13.5, fontWeight: "600", color: colors.onDim },
  stamp: {
    position: "absolute",
    top: 22,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 3,
  },
  stampKeep: { left: 20, borderColor: colors.accent, transform: [{ rotate: "-12deg" }] },
  stampSkip: { right: 20, borderColor: colors.onDim, transform: [{ rotate: "12deg" }] },
  stampText: { fontSize: 22, fontWeight: "900", letterSpacing: 1, color: colors.onDim },
  stampKeepText: { color: colors.accent },
  hint: { marginTop: spacing.md, fontSize: 12.5, color: colors.sec, textAlign: "center" },
  error: { marginTop: 6, fontSize: 12.5, color: colors.accentText, textAlign: "center" },
  undo: {
    alignSelf: "center",
    minHeight: 52,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  undoText: { fontSize: 14, fontWeight: "700", color: colors.onDim },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: spacing.sm,
  },
  dimmed: { opacity: 0.5 },
  skip: {
    flex: 1,
    height: 56,
    flexDirection: "row",
    gap: 6,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.fill,
  },
  skipText: { fontSize: 16, fontWeight: "800", color: colors.onDim },
  keep: {
    flex: 1,
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 28,
    backgroundColor: colors.accent,
  },
  keepText: { fontSize: 16, fontWeight: "800", color: colors.onImage },
  doneTitle: { fontSize: 20, fontWeight: "800", letterSpacing: -0.4, color: colors.ink },
  finishButton: {
    marginTop: spacing.sm,
    paddingHorizontal: 22,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.fillStrong,
  },
  finishText: { fontSize: 15, fontWeight: "700", color: colors.ink },
});
