from collections.abc import Sequence

from alembic import op

revision: str = "0020_spot_embeddings_gallery"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATEMENTS: tuple[str, ...] = (
    """
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
""",
    """
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
""",
    """
CREATE FUNCTION public.invalidate_overseas_spot_embedding() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            NEW.embedding = NULL;
            RETURN NEW;
        END;
        $$;
""",
    """
CREATE FUNCTION public.invalidate_spot_image_derivatives() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    DELETE FROM spot_embeddings
    WHERE content_id = NEW.content_id
      AND (
          NEW.first_image_url IS NULL
          OR NEW.first_image_url = ''
          OR image_url IS DISTINCT FROM NEW.first_image_url
      );
    DELETE FROM spot_embeddings_gallery
    WHERE content_id = NEW.content_id
      AND (
          NEW.first_image_url IS NULL
          OR NEW.first_image_url = ''
          OR image_url IS DISTINCT FROM NEW.first_image_url
      );
    IF NEW.first_image_url IS NULL OR NEW.first_image_url = '' THEN
        DELETE FROM embedding_failures
        WHERE content_id = NEW.content_id;
    ELSE
        INSERT INTO embedding_failures (content_id, reason, last_error)
        VALUES (NEW.content_id, 'source_changed', NULL)
        ON CONFLICT (content_id) DO UPDATE
        SET reason = EXCLUDED.reason,
            last_error = EXCLUDED.last_error;
    END IF;
    RETURN NEW;
END;
$$;
""",
    """
SET default_tablespace = '';
""",
    """
SET default_table_access_method = heap;
""",
    """
CREATE TABLE public.admin_users (
    username character varying(64) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.curation_spots (
    curation_id bigint NOT NULL,
    content_id character varying(32) NOT NULL,
    "position" integer NOT NULL
);
""",
    """
CREATE TABLE public.curations (
    id bigint NOT NULL,
    type character varying(16) NOT NULL,
    slug character varying(80) NOT NULL,
    title text NOT NULL,
    subtitle text,
    lead text,
    intro text,
    cover_spot_id character varying(32),
    region_cd character varying(8),
    mood_id smallint,
    is_published boolean DEFAULT false NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_curation_scope CHECK (((((type)::text = 'region'::text) AND (region_cd IS NOT NULL)) OR (((type)::text = 'mood'::text) AND (mood_id IS NOT NULL)) OR ((type)::text = 'editorial'::text))),
    CONSTRAINT ck_curation_type CHECK (((type)::text = ANY ((ARRAY['region'::character varying, 'mood'::character varying, 'editorial'::character varying])::text[])))
);
""",
    """
ALTER TABLE public.curations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
""",
    """
CREATE TABLE public.embedding_failures (
    content_id character varying(32) NOT NULL,
    reason character varying(32) NOT NULL,
    attempts integer DEFAULT 1 NOT NULL,
    last_error text,
    first_failed_at timestamp with time zone DEFAULT now() NOT NULL,
    last_attempt_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.lcls_systm_codes (
    lcls_systm3_cd character varying(16) NOT NULL,
    lcls_systm2_cd character varying(16),
    lcls_systm1_cd character varying(16),
    lcls_systm3_nm character varying(100) NOT NULL,
    lcls_systm2_nm character varying(100),
    lcls_systm1_nm character varying(100)
);
""",
    """
CREATE TABLE public.moods (
    id smallint NOT NULL,
    code character varying(16) NOT NULL,
    name character varying(32) NOT NULL,
    emoji character varying(8) NOT NULL,
    sort_order smallint NOT NULL
);
""",
    """
CREATE SEQUENCE public.moods_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
""",
    """
ALTER SEQUENCE public.moods_id_seq OWNED BY public.moods.id;
""",
    """
CREATE TABLE public.overseas_spots (
    id bigint NOT NULL,
    wikidata_id character varying(32) NOT NULL,
    name_ko character varying(255) NOT NULL,
    name_en character varying(255),
    country_code character varying(2) NOT NULL,
    country_name_ko character varying(80) NOT NULL,
    description_ko text,
    image_url text NOT NULL,
    image_author text,
    image_license character varying(80),
    image_license_url text,
    image_source_url text NOT NULL,
    fame_score integer DEFAULT 0 NOT NULL,
    category character varying(40),
    lat double precision,
    lng double precision,
    is_hidden boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    embedding public.halfvec(512)
);
""",
    """
ALTER TABLE public.overseas_spots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overseas_spots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
""",
    """
CREATE TABLE public.regions (
    ldong_regn_cd character varying(8) NOT NULL,
    ldong_regn_nm character varying(50) NOT NULL
);
""",
    """
CREATE TABLE public.sigungus (
    ldong_signgu_cd character varying(8) NOT NULL,
    ldong_regn_cd character varying(8) NOT NULL,
    ldong_signgu_nm character varying(50) NOT NULL
);
""",
    """
CREATE TABLE public.spot_concentration (
    content_id character varying(32) NOT NULL,
    concentration_rate numeric(5,2) NOT NULL,
    base_ymd date NOT NULL,
    raw_name character varying(255) NOT NULL,
    signgu_cd character varying(8),
    collected_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_spot_concentration_rate_range CHECK (((concentration_rate >= (0)::numeric) AND (concentration_rate <= (100)::numeric)))
);
""",
    """
CREATE TABLE public.spot_details (
    content_id character varying(32) NOT NULL,
    content_type_id smallint NOT NULL,
    intro_data jsonb,
    info_data jsonb,
    homepage character varying(500),
    tel character varying(50),
    cached_at timestamp with time zone DEFAULT now() NOT NULL,
    overview text
);
""",
    """
CREATE TABLE public.spot_embeddings (
    content_id character varying(32) NOT NULL,
    embedding public.halfvec(512) NOT NULL,
    image_url character varying(500),
    computed_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.spot_embeddings_gallery (
    content_id character varying(32) NOT NULL,
    embedding public.halfvec(512) NOT NULL,
    image_url character varying(500) NOT NULL,
    image_count smallint NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.spot_images (
    id bigint NOT NULL,
    content_id character varying(32) NOT NULL,
    origin_image_url character varying(500) NOT NULL,
    small_image_url character varying(500),
    cpyrht_div_cd character varying(8),
    serial_num character varying(32),
    sort_order smallint DEFAULT 0 NOT NULL
);
""",
    """
CREATE SEQUENCE public.spot_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
""",
    """
ALTER SEQUENCE public.spot_images_id_seq OWNED BY public.spot_images.id;
""",
    """
CREATE TABLE public.spot_moods (
    content_id character varying(32) NOT NULL,
    mood_id smallint NOT NULL,
    confidence double precision NOT NULL,
    source character varying(16) NOT NULL,
    CONSTRAINT ck_spot_mood_confidence CHECK (((confidence >= (0.0)::double precision) AND (confidence <= (1.0)::double precision))),
    CONSTRAINT ck_spot_mood_source CHECK (((source)::text = ANY ((ARRAY['code'::character varying, 'image'::character varying, 'manual'::character varying])::text[])))
);
""",
    """
CREATE TABLE public.spots (
    content_id character varying(32) NOT NULL,
    content_type_id smallint NOT NULL,
    title character varying(255) NOT NULL,
    addr1 character varying(255),
    addr2 character varying(255),
    zipcode character varying(16),
    mapx numeric(11,8),
    mapy numeric(10,8),
    ldong_regn_cd character varying(8),
    ldong_signgu_cd character varying(8),
    lcls_systm1 character varying(16),
    lcls_systm2 character varying(16),
    lcls_systm3 character varying(16),
    cpyrht_div_cd character varying(8),
    first_image_url character varying(500),
    first_image2_url character varying(500),
    show_flag smallint DEFAULT 1 NOT NULL,
    modified_time timestamp with time zone,
    synced_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_spot_cpyrht_div_cd CHECK (((cpyrht_div_cd IS NULL) OR ((cpyrht_div_cd)::text = ANY ((ARRAY['Type1'::character varying, 'Type3'::character varying])::text[])))),
    CONSTRAINT ck_spot_show_flag CHECK ((show_flag = ANY (ARRAY[0, 1])))
);
""",
    """
CREATE TABLE public.user_auth_providers (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(16) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    linked_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_auth_provider_value CHECK (((provider)::text = ANY ((ARRAY['kakao'::character varying, 'google'::character varying, 'apple'::character varying, 'email'::character varying])::text[])))
);
""",
    """
CREATE SEQUENCE public.user_auth_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
""",
    """
ALTER SEQUENCE public.user_auth_providers_id_seq OWNED BY public.user_auth_providers.id;
""",
    """
CREATE TABLE public.user_consents (
    user_id bigint NOT NULL,
    location_consent boolean DEFAULT false NOT NULL,
    photo_consent boolean DEFAULT false NOT NULL,
    terms_version character varying(16) NOT NULL,
    consented_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.user_saved_spots (
    user_id bigint NOT NULL,
    content_id character varying(32) NOT NULL,
    saved_at timestamp with time zone DEFAULT now() NOT NULL
);
""",
    """
CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(50),
    bio character varying(255),
    location_label character varying(100),
    profile_image_url character varying(500),
    taste_vector public.halfvec(512),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    password_hash character varying(255)
);
""",
    """
CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
""",
    """
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
""",
    """
ALTER TABLE ONLY public.moods ALTER COLUMN id SET DEFAULT nextval('public.moods_id_seq'::regclass);
""",
    """
ALTER TABLE ONLY public.spot_images ALTER COLUMN id SET DEFAULT nextval('public.spot_images_id_seq'::regclass);
""",
    """
ALTER TABLE ONLY public.user_auth_providers ALTER COLUMN id SET DEFAULT nextval('public.user_auth_providers_id_seq'::regclass);
""",
    """
ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
""",
    """
ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (username);
""",
    """
ALTER TABLE ONLY public.curation_spots
    ADD CONSTRAINT curation_spots_pkey PRIMARY KEY (curation_id, content_id);
""",
    """
ALTER TABLE ONLY public.curations
    ADD CONSTRAINT curations_pkey PRIMARY KEY (id);
""",
    """
ALTER TABLE ONLY public.embedding_failures
    ADD CONSTRAINT embedding_failures_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.lcls_systm_codes
    ADD CONSTRAINT lcls_systm_codes_pkey PRIMARY KEY (lcls_systm3_cd);
""",
    """
ALTER TABLE ONLY public.moods
    ADD CONSTRAINT moods_code_key UNIQUE (code);
""",
    """
ALTER TABLE ONLY public.moods
    ADD CONSTRAINT moods_pkey PRIMARY KEY (id);
""",
    """
ALTER TABLE ONLY public.overseas_spots
    ADD CONSTRAINT overseas_spots_pkey PRIMARY KEY (id);
""",
    """
ALTER TABLE ONLY public.regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (ldong_regn_cd);
""",
    """
ALTER TABLE ONLY public.sigungus
    ADD CONSTRAINT sigungus_pkey PRIMARY KEY (ldong_signgu_cd);
""",
    """
ALTER TABLE ONLY public.spot_concentration
    ADD CONSTRAINT spot_concentration_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.spot_details
    ADD CONSTRAINT spot_details_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.spot_embeddings_gallery
    ADD CONSTRAINT spot_embeddings_gallery_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.spot_embeddings
    ADD CONSTRAINT spot_embeddings_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.spot_images
    ADD CONSTRAINT spot_images_pkey PRIMARY KEY (id);
""",
    """
ALTER TABLE ONLY public.spot_moods
    ADD CONSTRAINT spot_moods_pkey PRIMARY KEY (content_id, mood_id);
""",
    """
ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_pkey PRIMARY KEY (content_id);
""",
    """
ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT uq_auth_provider_account UNIQUE (provider, provider_user_id);
""",
    """
ALTER TABLE ONLY public.curations
    ADD CONSTRAINT uq_curations_slug UNIQUE (slug);
""",
    """
ALTER TABLE ONLY public.overseas_spots
    ADD CONSTRAINT uq_overseas_spots_wikidata_id UNIQUE (wikidata_id);
""",
    """
ALTER TABLE ONLY public.spot_images
    ADD CONSTRAINT uq_spot_images_content_sort UNIQUE (content_id, sort_order);
""",
    """
ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT user_auth_providers_pkey PRIMARY KEY (id);
""",
    """
ALTER TABLE ONLY public.user_consents
    ADD CONSTRAINT user_consents_pkey PRIMARY KEY (user_id);
""",
    """
ALTER TABLE ONLY public.user_saved_spots
    ADD CONSTRAINT user_saved_spots_pkey PRIMARY KEY (user_id, content_id);
""",
    """
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
""",
    """
CREATE INDEX idx_auth_providers_user ON public.user_auth_providers USING btree (user_id);
""",
    """
CREATE INDEX idx_curation_spots_order ON public.curation_spots USING btree (curation_id, "position");
""",
    """
CREATE INDEX idx_curations_feed ON public.curations USING btree (type, is_published, "position");
""",
    """
CREATE INDEX idx_embedding_failures_reason ON public.embedding_failures USING btree (reason);
""",
    """
CREATE INDEX idx_overseas_spots_hnsw ON public.overseas_spots USING hnsw (embedding public.halfvec_cosine_ops) WITH (m='16', ef_construction='128');
""",
    """
CREATE INDEX idx_overseas_spots_visible ON public.overseas_spots USING btree (is_hidden, fame_score DESC);
""",
    """
CREATE INDEX idx_spot_concentration_rate ON public.spot_concentration USING btree (concentration_rate DESC);
""",
    """
CREATE INDEX idx_spot_details_cached ON public.spot_details USING btree (cached_at);
""",
    """
CREATE INDEX idx_spot_embeddings_gallery_hnsw ON public.spot_embeddings_gallery USING hnsw (embedding public.halfvec_cosine_ops) WITH (m='16', ef_construction='128');
""",
    """
CREATE INDEX idx_spot_embeddings_hnsw ON public.spot_embeddings USING hnsw (embedding public.halfvec_cosine_ops) WITH (m='16', ef_construction='128');
""",
    """
CREATE INDEX idx_spot_moods_mood ON public.spot_moods USING btree (mood_id, confidence DESC);
""",
    """
CREATE INDEX idx_spots_active_lcls ON public.spots USING btree (lcls_systm3) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_active_location ON public.spots USING btree (mapx, mapy) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_active_region ON public.spots USING btree (ldong_regn_cd, ldong_signgu_cd) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_active_type ON public.spots USING btree (content_type_id) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_addr1_trgm ON public.spots USING gin (addr1 public.gin_trgm_ops) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_image_pool ON public.spots USING btree (ldong_regn_cd) WHERE ((show_flag = 1) AND (first_image_url IS NOT NULL));
""",
    """
CREATE INDEX idx_spots_modified ON public.spots USING btree (modified_time DESC);
""",
    """
CREATE INDEX idx_spots_title_trgm ON public.spots USING gin (title public.gin_trgm_ops) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_spots_visible ON public.spots USING btree (show_flag) WHERE (show_flag = 1);
""",
    """
CREATE INDEX idx_user_saved_spots_user ON public.user_saved_spots USING btree (user_id, saved_at DESC);
""",
    """
CREATE UNIQUE INDEX idx_users_email_active ON public.users USING btree (email) WHERE (deleted_at IS NULL);
""",
    """
CREATE INDEX idx_users_taste_vector ON public.users USING ivfflat (taste_vector public.halfvec_cosine_ops);
""",
    """
CREATE INDEX ix_sigungus_ldong_regn_cd ON public.sigungus USING btree (ldong_regn_cd);
""",
    """
CREATE INDEX ix_spot_images_content_id ON public.spot_images USING btree (content_id);
""",
    """
CREATE TRIGGER trg_overseas_spots_invalidate_embedding BEFORE UPDATE OF image_url ON public.overseas_spots FOR EACH ROW WHEN ((old.image_url IS DISTINCT FROM new.image_url)) EXECUTE FUNCTION public.invalidate_overseas_spot_embedding();
""",
    """
CREATE TRIGGER trg_spots_invalidate_image_derivatives AFTER UPDATE OF first_image_url ON public.spots FOR EACH ROW WHEN (((old.first_image_url)::text IS DISTINCT FROM (new.first_image_url)::text)) EXECUTE FUNCTION public.invalidate_spot_image_derivatives();
""",
    """
ALTER TABLE ONLY public.curation_spots
    ADD CONSTRAINT curation_spots_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.curation_spots
    ADD CONSTRAINT curation_spots_curation_id_fkey FOREIGN KEY (curation_id) REFERENCES public.curations(id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.curations
    ADD CONSTRAINT curations_cover_spot_id_fkey FOREIGN KEY (cover_spot_id) REFERENCES public.spots(content_id) ON DELETE SET NULL;
""",
    """
ALTER TABLE ONLY public.curations
    ADD CONSTRAINT curations_mood_id_fkey FOREIGN KEY (mood_id) REFERENCES public.moods(id);
""",
    """
ALTER TABLE ONLY public.curations
    ADD CONSTRAINT curations_region_cd_fkey FOREIGN KEY (region_cd) REFERENCES public.regions(ldong_regn_cd);
""",
    """
ALTER TABLE ONLY public.embedding_failures
    ADD CONSTRAINT embedding_failures_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.sigungus
    ADD CONSTRAINT sigungus_ldong_regn_cd_fkey FOREIGN KEY (ldong_regn_cd) REFERENCES public.regions(ldong_regn_cd);
""",
    """
ALTER TABLE ONLY public.spot_concentration
    ADD CONSTRAINT spot_concentration_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_details
    ADD CONSTRAINT spot_details_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_embeddings
    ADD CONSTRAINT spot_embeddings_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_embeddings_gallery
    ADD CONSTRAINT spot_embeddings_gallery_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_images
    ADD CONSTRAINT spot_images_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_moods
    ADD CONSTRAINT spot_moods_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.spot_moods
    ADD CONSTRAINT spot_moods_mood_id_fkey FOREIGN KEY (mood_id) REFERENCES public.moods(id);
""",
    """
ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_lcls_systm3_fkey FOREIGN KEY (lcls_systm3) REFERENCES public.lcls_systm_codes(lcls_systm3_cd);
""",
    """
ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_ldong_regn_cd_fkey FOREIGN KEY (ldong_regn_cd) REFERENCES public.regions(ldong_regn_cd);
""",
    """
ALTER TABLE ONLY public.spots
    ADD CONSTRAINT spots_ldong_signgu_cd_fkey FOREIGN KEY (ldong_signgu_cd) REFERENCES public.sigungus(ldong_signgu_cd);
""",
    """
ALTER TABLE ONLY public.user_auth_providers
    ADD CONSTRAINT user_auth_providers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.user_consents
    ADD CONSTRAINT user_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.user_saved_spots
    ADD CONSTRAINT user_saved_spots_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.spots(content_id) ON DELETE CASCADE;
""",
    """
ALTER TABLE ONLY public.user_saved_spots
    ADD CONSTRAINT user_saved_spots_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
""",
    """
INSERT INTO public.admin_users (username, password_hash) VALUES
	('admin', '$2b$12$LS9LEWkjuCO8swgmNYpdn.0TybxJFd3ILOhphgynNYlFqbXWKd3ra');
""",
    """
INSERT INTO public.moods VALUES
	(1, 'sea', '바다', '🌊', 1),
	(2, 'mountain', '산·숲', '⛰️', 2),
	(3, 'lake', '호수', '🏞️', 3),
	(4, 'island', '섬', '🏝️', 4),
	(5, 'hanok', '한옥·고궁', '🏛️', 5),
	(6, 'night', '야경', '🌃', 6),
	(7, 'market', '시장', '🛍️', 7),
	(8, 'street', '도시 골목', '🏙️', 8);
""",
    """
INSERT INTO public.regions VALUES
	('11', '서울특별시'),
	('26', '부산광역시'),
	('27', '대구광역시'),
	('28', '인천광역시'),
	('29', '광주광역시'),
	('30', '대전광역시'),
	('31', '울산광역시'),
	('36', '세종특별자치시'),
	('41', '경기도'),
	('43', '충청북도'),
	('44', '충청남도'),
	('46', '전라남도'),
	('47', '경상북도'),
	('48', '경상남도'),
	('50', '제주특별자치도'),
	('51', '강원특별자치도'),
	('52', '전북특별자치도');
""",
    """
SELECT setval('public.moods_id_seq', (SELECT max(id) FROM public.moods));
""",
)


def upgrade() -> None:
    for statement in STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    raise NotImplementedError
